name: viser_bank
description: A new Flutter project.

publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  circular_countdown_timer: ^0.2.3
#  connectivity_plus: ^6.0.5
  country_picker: ^2.0.26
  cupertino_icons: ^1.0.2
  dio: ^5.6.0
  dotted_border: ^2.0.0+2
  equatable: ^2.0.5
  file_picker: any
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.2.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.0
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: any
  lottie: ^3.1.2
  open_file: ^3.5.3
  otp_timer_button: ^1.1.0
  path_provider: ^2.1.4
  percent_indicator: ^4.2.2
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboard/
    - assets/images/menu/
    - assets/images/social/
    - assets/images/app_logo/
    - assets/images/common/
    - assets/images/transfer/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700
